# Generated By: Claude Code (Claude Opus 4.6)
# Apache 2.0 License

MAKEFLAGS += --no-print-directory

.PHONY: all check test-lint-json test-lint-python test-lint-shell test-lint-compose help

all: check

check: test-lint-json test-lint-python test-lint-shell test-lint-compose  ## Run full quality gate

test-lint-json:  ## Validate dashboard JSON syntax and required fields
	@echo "==> Validating dashboard JSON"
	@fail=0; for f in dashboards/*.json; do \
		python3 -m json.tool "$$f" > /dev/null 2>&1 || { echo "FAIL: $$f"; fail=1; }; \
	done; \
	if [ $$fail -eq 1 ]; then exit 1; fi
	@echo "==> Checking dashboard required fields (uid, title)"
	@fail=0; for f in dashboards/*.json; do \
		python3 -c "import json,sys; d=json.load(open('$$f')); missing=[k for k in ('uid','title') if k not in d]; sys.exit(1) if missing else None" 2>/dev/null \
		|| { echo "FAIL: $$f missing uid or title"; fail=1; }; \
	done; \
	if [ $$fail -eq 1 ]; then exit 1; fi
	@echo "OK"

test-lint-python:  ## Compile-check Python scripts
	@echo "==> Compiling Python"
	python3 -m py_compile bin/dashboard-sync.py
	@echo "OK"

test-lint-shell:  ## Lint shell scripts with shellcheck
	@echo "==> Checking shell scripts"
	@if command -v shellcheck > /dev/null 2>&1; then \
		shellcheck bin/claude-wrapper.sh && echo "OK"; \
	else \
		echo "SKIP: shellcheck not installed"; \
	fi

test-lint-compose:  ## Validate docker-compose.yml
	@echo "==> Validating docker-compose.yml"
	podman-compose config > /dev/null
	@echo "OK"

help:  ## Show available targets
	@grep -hE '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

.DEFAULT_GOAL := all
