# Generated By: Claude Code (Claude Opus 4.6)
# Apache 2.0 License

MAKEFLAGS += --no-print-directory

# Compose tool autodetect — prefer docker compose (universal in CI), fall back to podman-compose, then docker-compose
COMPOSE := $(shell command -v docker > /dev/null 2>&1 && docker compose version > /dev/null 2>&1 && echo "docker compose" || command -v podman-compose 2>/dev/null || command -v docker-compose 2>/dev/null)

.PHONY: all check test-lint-json test-lint-python test-lint-shell test-lint-compose local-up local-down local-restart local-logs help

all: check

check: test-lint-json test-lint-python test-lint-shell test-lint-compose  ## Run full quality gate

test-lint-json:  ## Validate dashboard JSON syntax and required fields
	@echo "==> Validating dashboard JSON"
	@fail=0; for f in dashboards/*.json; do \
		python3 -m json.tool "$$f" > /dev/null 2>&1 || { echo "FAIL: $$f"; fail=1; }; \
	done; \
	if [ $$fail -eq 1 ]; then exit 1; fi
	@echo "==> Checking dashboard required fields (uid, title)"
	@fail=0; for f in dashboards/*.json; do \
		python3 -c "import json,sys; d=json.load(open('$$f')); missing=[k for k in ('uid','title') if k not in d]; sys.exit(1) if missing else None" 2>/dev/null \
		|| { echo "FAIL: $$f missing uid or title"; fail=1; }; \
	done; \
	if [ $$fail -eq 1 ]; then exit 1; fi
	@echo "OK"

test-lint-python:  ## Compile-check Python scripts
	@echo "==> Compiling Python"
	python3 -m py_compile bin/dashboard-sync.py
	@echo "OK"

test-lint-shell:  ## Lint shell scripts with shellcheck
	@echo "==> Checking shell scripts"
	@if command -v shellcheck > /dev/null 2>&1; then \
		shellcheck bin/claude-wrapper.sh && echo "OK"; \
	else \
		echo "SKIP: shellcheck not installed"; \
	fi

test-lint-compose:  ## Validate docker-compose.yml
	@if [ -z "$(COMPOSE)" ]; then \
		echo "==> SKIP: no compose tool found (install docker, podman-compose, or docker-compose)"; \
	else \
		echo "==> Validating docker-compose.yml using $(COMPOSE)"; \
		$(COMPOSE) -f docker-compose.yml config > /dev/null && echo "OK"; \
	fi

local-up:  ## Start local Grafana on :3001 pointed at tailscale Prom/Loki/Tempo
	podman-compose -f docker-compose.local.yml up -d
	@echo "Grafana: http://localhost:3001"

local-down:  ## Stop local Grafana (keeps volume)
	podman-compose -f docker-compose.local.yml down

local-restart:  ## Restart local Grafana stack
	podman-compose -f docker-compose.local.yml restart

local-logs:  ## Tail local Grafana + dashboard-sync logs
	podman-compose -f docker-compose.local.yml logs -f

help:  ## Show available targets
	@grep -hE '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

.DEFAULT_GOAL := all
