#!/bin/bash
# Generated By: Claude Code (claude-opus-5-5[1m])
#
# Self-check for bin/claude and bin/codex against stub native CLIs named by
# CLAUDE_CMD/CODEX_CMD: passthrough of args, stdin and exit status, no
# recursion, headless tagging, and which environment wins on host vs sandbox.

set -u

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
fail=0

check() {  # check <description> <expected> <actual>
    if [[ "$2" == "$3" ]]; then
        echo "ok   $1"
    else
        echo "FAIL $1"
        echo "     expected: $2"
        echo "     actual:   $3"
        fail=1
    fi
}

# Stub native CLIs: report what they received, exit with $STUB_EXIT.
mkdir -p "$TMP/native"
for name in claude codex; do
    cat > "$TMP/native/$name" <<'EOF'
#!/bin/bash
printf 'arg=%s\n' "$@"
echo "attrs=${OTEL_RESOURCE_ATTRIBUTES:-}"
echo "endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:-}"
echo "codex_project=${CODEX_PROJECT:-}"
[[ -t 0 ]] || echo "stdin=$(cat)"
exit "${STUB_EXIT:-0}"
EOF
    chmod +x "$TMP/native/$name"
done
export CLAUDE_CMD="$TMP/native/claude" CODEX_CMD="$TMP/native/codex"

# Host and sandbox layouts: the same shims, with bin/claude's /sandbox/.env
# check pointed at a file that is absent (host) or present (sandbox), so the
# result does not depend on where this test runs.
touch "$TMP/sandbox.env"
for layout in host sandbox; do
    mkdir -p "$TMP/$layout-bin"
    cp "$REPO_ROOT/bin/codex" "$TMP/$layout-bin/"
done
sed "s|/sandbox/\.env|$TMP/absent.env|g" "$REPO_ROOT/bin/claude" > "$TMP/host-bin/claude"
sed "s|/sandbox/\.env|$TMP/sandbox.env|g" "$REPO_ROOT/bin/claude" > "$TMP/sandbox-bin/claude"
chmod +x "$TMP/host-bin/claude" "$TMP/sandbox-bin/claude"

# A symlink to the wrapper earlier on PATH than the wrapper itself.
mkdir -p "$TMP/link"
ln -s "$REPO_ROOT/bin/claude" "$TMP/link/claude"

HOST_PATH="$TMP/host-bin:/usr/bin:/bin"
SANDBOX_PATH="$TMP/sandbox-bin:/usr/bin:/bin"

# timeout turns a recursion into a failure instead of a hang.
run() {  # run <PATH> <cmd> [args...]
    local path="$1"
    shift
    PATH="$path" timeout 5 "$@" < /dev/null
}

# --- passthrough -------------------------------------------------------------
out="$(PATH="$HOST_PATH" timeout 5 claude "a b" "" 'c"d' <<< "piped")"
check "claude: args with spaces, empty, quotes" \
    $'arg=a b\narg=\narg=c"d' "$(grep '^arg=' <<< "$out")"
check "claude: stdin passes through" "stdin=piped" "$(grep '^stdin=' <<< "$out")"

STUB_EXIT=7 run "$HOST_PATH" claude > /dev/null
check "claude: exit status passes through" 7 "$?"
STUB_EXIT=7 run "$HOST_PATH" codex > /dev/null
check "codex: exit status passes through" 7 "$?"

out="$(PATH="$HOST_PATH" timeout 5 codex "x y" <<< "piped")"
check "codex: args and stdin pass through" $'arg=x y\nstdin=piped' \
    "$(grep -e '^arg=' -e '^stdin=' <<< "$out")"

# --- no recursion ------------------------------------------------------------
out="$(run "$TMP/link:$HOST_PATH" claude)"
check "claude: symlinked wrapper first on PATH reaches native" 0 "$?"

# Several distinct shim copies on PATH: the native CLI is reached by path, so
# none of them may be exec'd (a PATH lookup ping-pongs until timeout, 124).
mkdir -p "$TMP/copy1" "$TMP/copy2" "$TMP/copy3"
for name in claude codex; do
    for dir in copy1 copy2 copy3; do
        cp "$REPO_ROOT/bin/$name" "$TMP/$dir/"
    done
    ln -s "$REPO_ROOT/bin/$name" "$TMP/link/$name" 2>/dev/null
    many_path="$TMP/copy1:$TMP/link:$TMP/copy2:$REPO_ROOT/bin:$TMP/copy3:/usr/bin:/bin"
    out="$(run "$many_path" "$name" marker)"
    check "$name: three copies + symlink + original on PATH, exits 0" 0 "$?"
    check "$name: three copies + symlink + original on PATH, reaches stub" \
        "arg=marker" "$(grep '^arg=' <<< "$out")"
done

CLAUDE_CMD="$TMP/missing" run "$HOST_PATH" claude > /dev/null 2>&1
check "claude: missing CLAUDE_CMD exits 127" 127 "$?"
CODEX_CMD="$TMP/missing" run "$HOST_PATH" codex > /dev/null 2>&1
check "codex: missing CODEX_CMD exits 127" 127 "$?"

# A bare name would be resolved on PATH, back to the shim.
CLAUDE_CMD=claude run "$HOST_PATH" claude > /dev/null 2>&1
check "claude: bare-name CLAUDE_CMD refused, not looped" 127 "$?"
CODEX_CMD=codex run "$HOST_PATH" codex > /dev/null 2>&1
check "codex: bare-name CODEX_CMD refused, not looped" 127 "$?"

# --- claude: host sets telemetry, sandbox keeps what it inherited ----------
check "test setup: sandbox check rewritten in host copy" 1 \
    "$(grep -c "! -f $TMP/absent.env" "$TMP/host-bin/claude")"

out="$(OTEL_EXPORTER_OTLP_ENDPOINT=http://inherited:4318 run "$HOST_PATH" claude)"
check "claude host: host endpoint applies" \
    "endpoint=http://localhost:4317" "$(grep '^endpoint=' <<< "$out")"
check "claude host: not headless without -p" "" "$(grep -o 'headless=true' <<< "$out")"

out="$(cd "$TMP" && OTEL_RESOURCE_ATTRIBUTES="review.run_id=x,project=/stale" \
    PATH="$HOST_PATH" timeout 5 claude -p < /dev/null)"
check "claude host: caller attrs win, absent ones added" \
    "review.run_id=x,project=/stale,headless=true" \
    "$(grep '^attrs=' <<< "$out" | grep -oE "project=[^,]*|review\.run_id=[^,]*|headless=true" | paste -sd, -)"

out="$(cd "$TMP" && env -u OTEL_RESOURCE_ATTRIBUTES PATH="$HOST_PATH" timeout 5 claude < /dev/null)"
check "claude host: fresh launch gets launch dir and base attrs" \
    "environment=dev,project=$TMP" \
    "$(grep '^attrs=' <<< "$out" | grep -oE "environment=[^,]*|project=[^,]*" | paste -sd, -)"

out="$(OTEL_EXPORTER_OTLP_ENDPOINT=http://inherited:4318 \
    OTEL_RESOURCE_ATTRIBUTES="project=/sb,sandbox.profile=home" \
    run "$SANDBOX_PATH" claude --print hi)"
check "claude sandbox: inherited endpoint kept" \
    "endpoint=http://inherited:4318" "$(grep '^endpoint=' <<< "$out")"
check "claude sandbox: inherited attrs kept, headless appended" \
    "attrs=project=/sb,sandbox.profile=home,headless=true" "$(grep '^attrs=' <<< "$out")"

out="$(OTEL_RESOURCE_ATTRIBUTES="project=/sb,headless=true" run "$SANDBOX_PATH" claude -p hi)"
check "claude: headless not duplicated for nested run" \
    "attrs=project=/sb,headless=true" "$(grep '^attrs=' <<< "$out")"

out="$(env -u OTEL_RESOURCE_ATTRIBUTES PATH="$SANDBOX_PATH" timeout 5 claude -p < /dev/null)"
check "claude sandbox: stripped nested run gets no project, no leading comma" \
    "attrs=headless=true" "$(grep '^attrs=' <<< "$out")"

# --- codex: project from launch dir, unless one is already present ---------
out="$(cd "$TMP" && env -u CODEX_PROJECT -u OTEL_RESOURCE_ATTRIBUTES \
    PATH="$HOST_PATH" timeout 5 codex < /dev/null)"
check "codex: CODEX_PROJECT is launch dir" "codex_project=$TMP" "$(grep '^codex_project=' <<< "$out")"
check "codex: project attr added when absent" "attrs=project=$TMP" "$(grep '^attrs=' <<< "$out")"

out="$(cd "$TMP" && env -u CODEX_PROJECT OTEL_RESOURCE_ATTRIBUTES="project=/sb,host.name=h" \
    PATH="$SANDBOX_PATH" timeout 5 codex < /dev/null)"
check "codex sandbox: existing project preserved" \
    "attrs=project=/sb,host.name=h" "$(grep '^attrs=' <<< "$out")"
check "codex sandbox: CODEX_PROJECT follows inherited project" \
    "codex_project=/sb" "$(grep '^codex_project=' <<< "$out")"

out="$(cd "$TMP" && env -u CODEX_PROJECT OTEL_RESOURCE_ATTRIBUTES="sandbox.project=x" \
    PATH="$SANDBOX_PATH" timeout 5 codex < /dev/null)"
check "codex: a key merely ending in project= does not count" \
    "attrs=sandbox.project=x,project=$TMP" "$(grep '^attrs=' <<< "$out")"

exit "$fail"
