#!/usr/bin/env python3
# Generated By: Claude Code (claude-opus-5[1m])
"""Measure the longest OTEL-silent stretch inside a Claude Code turn.

Sets the range window on claude_session_working empirically. That rule is a
timestamp comparison over a window W; W is exactly "the longest silent stretch
inside a turn that stays visible", and because a thinking session and a dead
one both emit nothing, the same W is how long a dead session reports WORKING.
One knob, both meanings.

A gap counts only if it lies inside a turn: consecutive activity events with no
Stop between them. Gaps spanning an idle period are excluded, which is why Stop
events are fetched alongside activity.

Run --self-check to exercise the walk without Loki.
"""

import argparse
import importlib.util
import json
import os
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

ACTIVITY = "api_request|tool_decision|tool_result|skill_activated|subagent_completed|user_prompt"
HOUSEKEEPING = {"away_summary", "compact", "generate_session_title"}
# Activity and Stop in one query: the walk needs them interleaved in time
# order, and the Stop filter is an OR of two different label shapes.
QUERY = (
    '{service_name="claude-code"}'
    f' | event_name =~ "{ACTIVITY}|hook_execution_complete"'
)
CANDIDATE_WINDOWS_SECONDS = (60, 300, 600, 1800)
DEFAULT_LOKI_URL = "http://127.0.0.1:3100"
NS_PER_SECOND = 1_000_000_000


def _load_fetch_events():
    """Reuse the exporter's day-bounded Loki paging rather than repeat it.

    Hyphenated module name, so importlib rather than a plain import.
    """
    path = Path(__file__).resolve().parent / "export-claude-otel-audit.py"
    spec = importlib.util.spec_from_file_location("claude_otel_audit", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.fetch_events


BLOCKING_TOOLS = {"AskUserQuestion", "ExitPlanMode"}


def classify(attrs):
    """Return "activity", "stop", "permission", or None for one event's labels."""
    event = attrs.get("event_name", "")
    if event == "hook_execution_complete":
        hook = attrs.get("hook_event")
        if hook == "Stop":
            return "stop"
        return "permission" if hook == "PermissionRequest" else None
    if event in ACTIVITY.split("|"):
        if attrs.get("query_source", "") in HOUSEKEEPING:
            return None
        return "activity"
    return None


def session_of(attrs):
    """Fold orchestrated children into their launching session, as the rule does."""
    return attrs.get("review_orchestrating_session_id") or attrs.get("session_id", "")


def intra_turn_gaps(events):
    """Every gap in nanoseconds between consecutive activity events in one turn.

    events: iterable of (timestamp_ns, attrs). Order is not assumed.
    """
    per_session = {}
    for timestamp, attrs in events:
        kind = classify(attrs)
        if kind is None:
            continue
        session = session_of(attrs)
        if not session:
            continue
        per_session.setdefault(session, []).append((timestamp, kind, attrs))

    gaps = []
    for session, records in per_session.items():
        records.sort(key=lambda item: item[0])
        previous = None
        previous_attrs = {}
        blocked = False
        for timestamp, kind, attrs in records:
            if kind == "stop":
                # Turn ended; the next activity starts a new one.
                previous, previous_attrs, blocked = None, {}, False
                continue
            if kind == "permission":
                # A dialog inside the gap: the session was waiting on a human,
                # not thinking. PERMISSION_REQUIRED outranks WORKING anyway.
                blocked = True
                continue
            if previous is not None:
                gaps.append({
                    "nanoseconds": timestamp - previous,
                    "session_id": session,
                    "started_at": previous,
                    "preceded_by": previous_attrs.get("event_name", ""),
                    "preceded_by_tool": previous_attrs.get("tool_name", ""),
                    "resumed_with": attrs.get("event_name", ""),
                    "resumed_with_tool": attrs.get("tool_name", ""),
                    "project": attrs.get("project", ""),
                    # A turn that never reached Stop and was ended by the user
                    # typing again was interrupted or died — not working.
                    "blocked_on_user": blocked
                    or previous_attrs.get("tool_name") in BLOCKING_TOOLS,
                    "ended_by_new_prompt": attrs.get("event_name") == "user_prompt",
                })
            previous, previous_attrs, blocked = timestamp, attrs, False
    return gaps


def percentile(sorted_values, fraction):
    if not sorted_values:
        return 0
    index = min(len(sorted_values) - 1, int(round(fraction * (len(sorted_values) - 1))))
    return sorted_values[index]


def _window_costs(seconds):
    return {
        f"{window}s": sum(1 for value in seconds if value > window)
        for window in CANDIDATE_WINDOWS_SECONDS
    }


def summarize(gaps):
    seconds = sorted(gap["nanoseconds"] / NS_PER_SECOND for gap in gaps)
    # The window only has to cover silence while the session was genuinely
    # working. Gaps spent at a permission dialog or a question, and gaps where
    # the turn never reached Stop and the user typed again, are not that.
    working = sorted(
        gap["nanoseconds"] / NS_PER_SECOND
        for gap in gaps
        if not gap["blocked_on_user"] and not gap["ended_by_new_prompt"]
    )
    return {
        "gaps": len(gaps),
        "working_gaps": len(working),
        "p50_seconds": round(percentile(seconds, 0.50), 1),
        "p90_seconds": round(percentile(seconds, 0.90), 1),
        "p99_seconds": round(percentile(seconds, 0.99), 1),
        "max_seconds": round(seconds[-1], 1) if seconds else 0,
        "working_p99_seconds": round(percentile(working, 0.99), 1),
        "working_max_seconds": round(working[-1], 1) if working else 0,
        # The decision numbers: a window of W drops every gap longer than W.
        # Size on working_only; all_gaps is there to show what was excluded.
        "turns_lost_by_window": {
            "all_gaps": _window_costs(seconds),
            "working_only": _window_costs(working),
        },
        "largest": [
            {
                "seconds": round(gap["nanoseconds"] / NS_PER_SECOND, 1),
                "session_id": gap["session_id"],
                "gap_started_at": datetime.fromtimestamp(
                    gap["started_at"] / NS_PER_SECOND, tz=timezone.utc
                ).isoformat(),
                "preceded_by": gap["preceded_by"],
                "preceded_by_tool": gap["preceded_by_tool"],
                "resumed_with": gap["resumed_with"],
                "resumed_with_tool": gap["resumed_with_tool"],
                "blocked_on_user": gap["blocked_on_user"],
                "ended_by_new_prompt": gap["ended_by_new_prompt"],
                "project": gap["project"],
            }
            for gap in sorted(gaps, key=lambda item: item["nanoseconds"], reverse=True)[:20]
        ],
    }


def self_check():
    """Synthetic walk: idle gaps excluded, intra-turn gaps measured, children folded."""
    second = NS_PER_SECOND

    def activity(name="api_request", session="s1", **extra):
        return {"event_name": name, "session_id": session, **extra}

    stop = {"event_name": "hook_execution_complete", "hook_event": "Stop", "session_id": "s1"}

    events = [
        (10 * second, activity("user_prompt")),
        (13 * second, activity()),            # 3s intra-turn gap
        (20 * second, stop),                  # turn ends
        (900 * second, activity("user_prompt")),  # idle gap, must NOT count
        (905 * second, activity()),           # 5s intra-turn gap
    ]
    measured = sorted(gap["nanoseconds"] / second for gap in intra_turn_gaps(events))
    assert measured == [3, 5], measured

    # Housekeeping is excluded, so the gap spans it rather than being split.
    events = [
        (0, activity("user_prompt")),
        (5 * second, activity(query_source="compact")),
        (30 * second, activity()),
    ]
    measured = sorted(gap["nanoseconds"] / second for gap in intra_turn_gaps(events))
    assert measured == [30], measured

    # A child's events belong to the launching session, not its own.
    events = [
        (0, activity("user_prompt", session="parent")),
        (7 * second, activity(session="child", review_orchestrating_session_id="parent")),
    ]
    gaps = intra_turn_gaps(events)
    assert len(gaps) == 1 and gaps[0]["session_id"] == "parent", gaps

    # A Stop for one session must not end another session's turn.
    events = [
        (0, activity("user_prompt", session="a")),
        (1 * second, {"event_name": "hook_execution_complete", "hook_event": "Stop", "session_id": "b"}),
        (4 * second, activity(session="a")),
    ]
    measured = sorted(gap["nanoseconds"] / second for gap in intra_turn_gaps(events))
    assert measured == [4], measured

    # A permission dialog inside the gap marks it blocked, not working.
    events = [
        (0, activity("user_prompt")),
        (2 * second, {"event_name": "hook_execution_complete", "hook_event": "PermissionRequest", "session_id": "s1"}),
        (600 * second, activity("tool_result")),
    ]
    gaps = intra_turn_gaps(events)
    assert len(gaps) == 1 and gaps[0]["blocked_on_user"], gaps

    # AskUserQuestion immediately before the gap marks it blocked too.
    events = [
        (0, activity("tool_decision", tool_name="AskUserQuestion")),
        (600 * second, activity("tool_result", tool_name="AskUserQuestion")),
    ]
    gaps = intra_turn_gaps(events)
    assert len(gaps) == 1 and gaps[0]["blocked_on_user"], gaps

    # A turn the user ended by typing again never reached Stop: not working.
    events = [
        (0, activity()),
        (600 * second, activity("user_prompt")),
    ]
    gaps = intra_turn_gaps(events)
    assert len(gaps) == 1 and gaps[0]["ended_by_new_prompt"] and not gaps[0]["blocked_on_user"], gaps

    # Ordinary in-turn silence stays working, and the split reaches summarize().
    events = [
        (0, activity("api_request")),
        (120 * second, activity("tool_decision")),
    ]
    report = summarize(intra_turn_gaps(events))
    assert report["gaps"] == 1 and report["working_gaps"] == 1, report
    assert report["turns_lost_by_window"]["working_only"]["60s"] == 1, report
    assert report["turns_lost_by_window"]["working_only"]["300s"] == 0, report

    print("self-check OK")


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--loki-url", default=os.environ.get("LOKI_URL", DEFAULT_LOKI_URL))
    parser.add_argument("--days", type=int, default=7)
    parser.add_argument("--output", help="write the full report as JSON here")
    parser.add_argument("--self-check", action="store_true", help="run the walk against synthetic events and exit")
    args = parser.parse_args()

    if args.self_check:
        self_check()
        return
    if args.days <= 0:
        parser.error("--days must be positive")

    fetch_events = _load_fetch_events()
    now = datetime.now(timezone.utc)
    events = fetch_events(args.loki_url, now - timedelta(days=args.days), now, QUERY)
    report = summarize(intra_turn_gaps(events))

    json.dump(report, sys.stdout, indent=2)
    sys.stdout.write("\n")
    if args.output:
        path = Path(args.output)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(report, indent=2) + "\n")
        print(f"Wrote {path}", file=sys.stderr)


if __name__ == "__main__":
    main()
